ALTER TABLE `cv` ALTER `id` DROP DEFAULT;
ALTER TABLE `cv` CHANGE COLUMN `id` `id` VARCHAR(50) NOT NULL FIRST;
ALTER TABLE `cv` DROP PRIMARY KEY;
ALTER TABLE `cv` CHANGE COLUMN `creation_date` `creation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `candidate_id`;
ALTER TABLE `cv` CHANGE COLUMN `creation_date` `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `candidate_id`;